// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using payment_service.Data;

#nullable disable

namespace payment_service.Migrations
{
    [DbContext(typeof(PaymentDbContext))]
    [Migration("20260726185514_AddPaymentResultOutbox")]
    partial class AddPaymentResultOutbox
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("payment_service.Models.EscrowRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("BookingId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("CustodyUserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("FundedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FundingTransactionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RefundTransactionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RefundedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReleaseTransactionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ReleasedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequesterUserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TaskMasterUserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique()
                        .HasDatabaseName("IX_escrows_booking_id");

                    b.HasIndex("FundingTransactionId")
                        .IsUnique()
                        .HasDatabaseName("IX_escrows_funding_transaction_id")
                        .HasFilter("\"FundingTransactionId\" IS NOT NULL");

                    b.HasIndex("RefundTransactionId")
                        .IsUnique()
                        .HasDatabaseName("IX_escrows_refund_transaction_id")
                        .HasFilter("\"RefundTransactionId\" IS NOT NULL");

                    b.HasIndex("ReleaseTransactionId")
                        .IsUnique()
                        .HasDatabaseName("IX_escrows_release_transaction_id")
                        .HasFilter("\"ReleaseTransactionId\" IS NOT NULL");

                    b.ToTable("escrows", null, t =>
                        {
                            t.HasCheckConstraint("CK_escrows_amount_positive", "\"Amount\" > 0");

                            t.HasCheckConstraint("CK_escrows_status_valid", "\"Status\" IN ('PENDING', 'FUNDED', 'RELEASED', 'REFUNDED')");
                        });
                });

            modelBuilder.Entity("payment_service.Models.PaymentMethodTokenRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MaskedCardNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("RedeemedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("SimulatesDecline")
                        .HasColumnType("boolean");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_payment_method_tokens_expires_at");

                    b.HasIndex("RedeemedAt")
                        .HasDatabaseName("IX_payment_method_tokens_redeemed_at");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("IX_payment_method_tokens_token_hash");

                    b.ToTable("payment_method_tokens", (string)null);
                });

            modelBuilder.Entity("payment_service.Models.PaymentResultOutbox", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DispatchAttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DispatchClaimExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DispatchClaimedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DispatchStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("DispatchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastDispatchError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("NextDispatchAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("SagaId")
                        .HasColumnType("uuid");

                    b.Property<string>("TraceParent")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SagaId")
                        .IsUnique()
                        .HasDatabaseName("IX_payment_result_outbox_saga_id");

                    b.HasIndex("TransactionId")
                        .IsUnique()
                        .HasDatabaseName("IX_payment_result_outbox_transaction_id");

                    b.HasIndex("DispatchStatus", "NextDispatchAttemptAt")
                        .HasDatabaseName("IX_payment_result_outbox_pending");

                    b.ToTable("payment_result_outbox", null, t =>
                        {
                            t.HasCheckConstraint("CK_payment_result_outbox_dispatch_status_valid", "\"DispatchStatus\" IN ('PENDING', 'CLAIMED', 'DISPATCHED')");
                        });
                });

            modelBuilder.Entity("payment_service.Models.PaymentTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("BookingId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("DeclineReason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("EscrowId")
                        .HasColumnType("uuid");

                    b.Property<string>("MaskedCardNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Operation")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PayeeUserId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PayerUserId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("SagaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TaskMasterUserId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("EscrowId")
                        .HasDatabaseName("IX_payment_transactions_escrow_id")
                        .HasFilter("\"EscrowId\" IS NOT NULL");

                    b.HasIndex("SagaId")
                        .IsUnique()
                        .HasDatabaseName("IX_payment_transactions_saga_id")
                        .HasFilter("\"SagaId\" IS NOT NULL");

                    b.ToTable("payment_transactions", null, t =>
                        {
                            t.HasCheckConstraint("CK_payment_transactions_amount_positive", "\"Amount\" > 0");
                        });
                });

            modelBuilder.Entity("payment_service.Models.UserWallet", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.ToTable("user_wallets", null, t =>
                        {
                            t.HasCheckConstraint("CK_user_wallets_balance_non_negative", "\"Balance\" >= 0");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
