// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using payment_service.Data;

#nullable disable

namespace payment_service.Migrations
{
    [DbContext(typeof(PaymentDbContext))]
    [Migration("20260815225533_AddLedgerCutoverState")]
    partial class AddLedgerCutoverState
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("payment_service.Models.EscrowRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("BookingId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("CustodyUserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("FundedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FundingTransactionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RefundTransactionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RefundedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReleaseTransactionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ReleasedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequesterUserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TaskMasterUserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique()
                        .HasDatabaseName("IX_escrows_booking_id");

                    b.HasIndex("FundingTransactionId")
                        .IsUnique()
                        .HasDatabaseName("IX_escrows_funding_transaction_id")
                        .HasFilter("\"FundingTransactionId\" IS NOT NULL");

                    b.HasIndex("RefundTransactionId")
                        .IsUnique()
                        .HasDatabaseName("IX_escrows_refund_transaction_id")
                        .HasFilter("\"RefundTransactionId\" IS NOT NULL");

                    b.HasIndex("ReleaseTransactionId")
                        .IsUnique()
                        .HasDatabaseName("IX_escrows_release_transaction_id")
                        .HasFilter("\"ReleaseTransactionId\" IS NOT NULL");

                    b.ToTable("escrows", null, t =>
                        {
                            t.HasCheckConstraint("CK_escrows_amount_positive", "\"Amount\" > 0");

                            t.HasCheckConstraint("CK_escrows_status_valid", "\"Status\" IN ('PENDING', 'FUNDED', 'RELEASED', 'REFUNDED')");
                        });
                });

            modelBuilder.Entity("payment_service.Models.JournalEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BookingId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("EscrowId")
                        .HasColumnType("uuid");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid?>("PaymentTransactionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ReversesJournalEntryId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SagaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .HasDatabaseName("IX_journal_entries_booking_id")
                        .HasFilter("\"BookingId\" IS NOT NULL");

                    b.HasIndex("EscrowId")
                        .HasDatabaseName("IX_journal_entries_escrow_id")
                        .HasFilter("\"EscrowId\" IS NOT NULL");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("IX_journal_entries_idempotency_key");

                    b.HasIndex("PaymentTransactionId")
                        .IsUnique()
                        .HasDatabaseName("IX_journal_entries_payment_transaction_id")
                        .HasFilter("\"PaymentTransactionId\" IS NOT NULL");

                    b.HasIndex("ReversesJournalEntryId")
                        .IsUnique()
                        .HasDatabaseName("IX_journal_entries_reverses_journal_entry_id")
                        .HasFilter("\"ReversesJournalEntryId\" IS NOT NULL");

                    b.HasIndex("SagaId")
                        .HasDatabaseName("IX_journal_entries_saga_id")
                        .HasFilter("\"SagaId\" IS NOT NULL");

                    b.ToTable("journal_entries", null, t =>
                        {
                            t.HasCheckConstraint("CK_journal_entries_currency_valid", "length(\"Currency\") = 3 AND \"Currency\" = upper(\"Currency\")");

                            t.HasCheckConstraint("CK_journal_entries_operation_valid", "\"Operation\" IN ('OPENING_BALANCE', 'USER_REGISTRATION_CREDIT', 'LEGACY_PAYMENT', 'FUND_ESCROW', 'RELEASE_ESCROW', 'REFUND_ESCROW', 'REVERSAL', 'ADMIN_ADJUSTMENT')");

                            t.HasCheckConstraint("CK_journal_entries_reversal_valid", "(\"Operation\" = 'REVERSAL' AND \"ReversesJournalEntryId\" IS NOT NULL) OR (\"Operation\" <> 'REVERSAL' AND \"ReversesJournalEntryId\" IS NULL)");
                        });
                });

            modelBuilder.Entity("payment_service.Models.JournalLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<Guid>("JournalEntryId")
                        .HasColumnType("uuid");

                    b.Property<short>("LineNumber")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("JournalEntryId", "LineNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_journal_lines_entry_line_number");

                    b.HasIndex("AccountId", "CreatedAt", "Id")
                        .HasDatabaseName("IX_journal_lines_account_created_id");

                    b.ToTable("journal_lines", null, t =>
                        {
                            t.HasCheckConstraint("CK_journal_lines_amount_positive", "\"Amount\" > 0");

                            t.HasCheckConstraint("CK_journal_lines_direction_valid", "\"Direction\" IN ('DEBIT', 'CREDIT')");

                            t.HasCheckConstraint("CK_journal_lines_line_number_positive", "\"LineNumber\" > 0");
                        });
                });

            modelBuilder.Entity("payment_service.Models.LedgerAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("OwnerUserId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Currency")
                        .IsUnique()
                        .HasDatabaseName("IX_ledger_accounts_system_issuance_currency")
                        .HasFilter("\"AccountType\" = 'SYSTEM_ISSUANCE'");

                    b.HasIndex("OwnerUserId", "AccountType", "Currency")
                        .IsUnique()
                        .HasDatabaseName("IX_ledger_accounts_owner_type_currency")
                        .HasFilter("\"OwnerUserId\" IS NOT NULL");

                    b.ToTable("ledger_accounts", null, t =>
                        {
                            t.HasCheckConstraint("CK_ledger_accounts_account_type_valid", "\"AccountType\" IN ('USER_WALLET', 'ESCROW_CUSTODY', 'SYSTEM_ISSUANCE')");

                            t.HasCheckConstraint("CK_ledger_accounts_closed_at_valid", "(\"Status\" = 'ACTIVE' AND \"ClosedAt\" IS NULL) OR (\"Status\" = 'CLOSED' AND \"ClosedAt\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_ledger_accounts_currency_valid", "length(\"Currency\") = 3 AND \"Currency\" = upper(\"Currency\")");

                            t.HasCheckConstraint("CK_ledger_accounts_owner_valid", "(\"AccountType\" = 'SYSTEM_ISSUANCE' AND \"OwnerUserId\" IS NULL) OR (\"AccountType\" <> 'SYSTEM_ISSUANCE' AND \"OwnerUserId\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_ledger_accounts_status_valid", "\"Status\" IN ('ACTIVE', 'CLOSED')");
                        });
                });

            modelBuilder.Entity("payment_service.Models.LedgerCutoverState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTime>("LedgerEpochAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WalletCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ledger_cutover_state", null, t =>
                        {
                            t.HasCheckConstraint("CK_ledger_cutover_state_currency_valid", "length(\"Currency\") = 3 AND \"Currency\" = upper(\"Currency\")");

                            t.HasCheckConstraint("CK_ledger_cutover_state_singleton", "\"Id\" = 1");

                            t.HasCheckConstraint("CK_ledger_cutover_state_wallet_count_non_negative", "\"WalletCount\" >= 0");
                        });
                });

            modelBuilder.Entity("payment_service.Models.PaymentMethodTokenRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MaskedCardNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("RedeemedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("SimulatesDecline")
                        .HasColumnType("boolean");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_payment_method_tokens_expires_at");

                    b.HasIndex("RedeemedAt")
                        .HasDatabaseName("IX_payment_method_tokens_redeemed_at");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("IX_payment_method_tokens_token_hash");

                    b.ToTable("payment_method_tokens", (string)null);
                });

            modelBuilder.Entity("payment_service.Models.PaymentResultOutbox", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DispatchAttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DispatchClaimExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DispatchClaimedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DispatchStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("DispatchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastDispatchError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("NextDispatchAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("SagaId")
                        .HasColumnType("uuid");

                    b.Property<string>("TraceParent")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SagaId")
                        .IsUnique()
                        .HasDatabaseName("IX_payment_result_outbox_saga_id");

                    b.HasIndex("TransactionId")
                        .IsUnique()
                        .HasDatabaseName("IX_payment_result_outbox_transaction_id");

                    b.HasIndex("DispatchStatus", "NextDispatchAttemptAt")
                        .HasDatabaseName("IX_payment_result_outbox_pending");

                    b.ToTable("payment_result_outbox", null, t =>
                        {
                            t.HasCheckConstraint("CK_payment_result_outbox_dispatch_status_valid", "\"DispatchStatus\" IN ('PENDING', 'CLAIMED', 'DISPATCHED')");
                        });
                });

            modelBuilder.Entity("payment_service.Models.PaymentTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("BookingId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("DeclineReason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("EscrowId")
                        .HasColumnType("uuid");

                    b.Property<string>("MaskedCardNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Operation")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PayeeUserId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PayerUserId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("SagaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TaskMasterUserId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("EscrowId")
                        .HasDatabaseName("IX_payment_transactions_escrow_id")
                        .HasFilter("\"EscrowId\" IS NOT NULL");

                    b.HasIndex("SagaId")
                        .IsUnique()
                        .HasDatabaseName("IX_payment_transactions_saga_id")
                        .HasFilter("\"SagaId\" IS NOT NULL");

                    b.ToTable("payment_transactions", null, t =>
                        {
                            t.HasCheckConstraint("CK_payment_transactions_amount_positive", "\"Amount\" > 0");
                        });
                });

            modelBuilder.Entity("payment_service.Models.UserWallet", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastJournalEntryId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LedgerAccountId")
                        .HasColumnType("uuid");

                    b.Property<long>("ProjectionVersion")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.HasIndex("LastJournalEntryId");

                    b.HasIndex("LedgerAccountId")
                        .IsUnique()
                        .HasDatabaseName("IX_user_wallets_ledger_account_id")
                        .HasFilter("\"LedgerAccountId\" IS NOT NULL");

                    b.ToTable("user_wallets", null, t =>
                        {
                            t.HasCheckConstraint("CK_user_wallets_balance_non_negative", "\"Balance\" >= 0");
                        });
                });

            modelBuilder.Entity("payment_service.Models.JournalEntry", b =>
                {
                    b.HasOne("payment_service.Models.PaymentTransaction", "PaymentTransaction")
                        .WithOne()
                        .HasForeignKey("payment_service.Models.JournalEntry", "PaymentTransactionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("payment_service.Models.JournalEntry", "ReversesJournalEntry")
                        .WithOne("ReversalJournalEntry")
                        .HasForeignKey("payment_service.Models.JournalEntry", "ReversesJournalEntryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PaymentTransaction");

                    b.Navigation("ReversesJournalEntry");
                });

            modelBuilder.Entity("payment_service.Models.JournalLine", b =>
                {
                    b.HasOne("payment_service.Models.LedgerAccount", "Account")
                        .WithMany("JournalLines")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("payment_service.Models.JournalEntry", "JournalEntry")
                        .WithMany("Lines")
                        .HasForeignKey("JournalEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("JournalEntry");
                });

            modelBuilder.Entity("payment_service.Models.UserWallet", b =>
                {
                    b.HasOne("payment_service.Models.JournalEntry", "LastJournalEntry")
                        .WithMany()
                        .HasForeignKey("LastJournalEntryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("payment_service.Models.LedgerAccount", "LedgerAccount")
                        .WithOne()
                        .HasForeignKey("payment_service.Models.UserWallet", "LedgerAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("LastJournalEntry");

                    b.Navigation("LedgerAccount");
                });

            modelBuilder.Entity("payment_service.Models.JournalEntry", b =>
                {
                    b.Navigation("Lines");

                    b.Navigation("ReversalJournalEntry");
                });

            modelBuilder.Entity("payment_service.Models.LedgerAccount", b =>
                {
                    b.Navigation("JournalLines");
                });
#pragma warning restore 612, 618
        }
    }
}
