spring:
  data:
    mongodb:
      port: ${mongo_port:27017}
      host: mongodb
      database: products
  application:
    name: product-service


logging:
  level:
    org.springframework.cloud.consul: INFO
server:
  port: 8080


